"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms.

4613732
"""

def fib(num):
	if (num<2):
		return 1
	return fib(num-1) + fib(num-2)


maxNum = 4000000
total = 0
myItt = 1
while(True):
	result = fib(myItt)
	if result > maxNum:
		break;
	print result
	if(result % 2 ==0):
		total += result
	myItt += 1
print
print total


